name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Login to Azure
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Login to ACR
    - name: Login to Azure Container Registry
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    # Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/myapp:${{ github.sha }} .

    # Push Docker image to ACR
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/myapp:${{ github.sha }}

    # Optionally tag 'latest'
    - name: Tag 'latest'
      run: |
        docker tag ${{ secrets.ACR_NAME }}.azurecr.io/myapp:${{ github.sha }} ${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/myapp:latest
